provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  slack-webhook-fn:
    lang: go
    handler: ./slack-webhook-fn
    image: viveksyngh/slack-webhook-fn
    secrets:
      - slack-webhook-url
